/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PostsYearRouteImport } from './routes/posts.$year'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as DashboardPostsRouteImport } from './routes/dashboard.posts'
import { Route as DashboardPostsPostIdRouteImport } from './routes/dashboard.posts.$postId'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsYearRoute = PostsYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/dashboard/posts',
  path: '/dashboard/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsPostIdRoute = DashboardPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => DashboardPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/write': typeof WriteRoute
  '/dashboard/posts': typeof DashboardPostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/write': typeof WriteRoute
  '/dashboard/posts': typeof DashboardPostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/write': typeof WriteRoute
  '/dashboard/posts': typeof DashboardPostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/posts'
    | '/write'
    | '/dashboard/posts'
    | '/posts/$postId'
    | '/posts/$year'
    | '/dashboard/'
    | '/dashboard/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/posts'
    | '/write'
    | '/dashboard/posts'
    | '/posts/$postId'
    | '/posts/$year'
    | '/dashboard'
    | '/dashboard/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/posts'
    | '/write'
    | '/dashboard/posts'
    | '/posts/$postId'
    | '/posts/$year'
    | '/dashboard/'
    | '/dashboard/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRouteWithChildren
  WriteRoute: typeof WriteRoute
  DashboardPostsRoute: typeof DashboardPostsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$year': {
      id: '/posts/$year'
      path: '/$year'
      fullPath: '/posts/$year'
      preLoaderRoute: typeof PostsYearRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/posts/$postId': {
      id: '/dashboard/posts/$postId'
      path: '/$postId'
      fullPath: '/dashboard/posts/$postId'
      preLoaderRoute: typeof DashboardPostsPostIdRouteImport
      parentRoute: typeof DashboardPostsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsYearRoute: typeof PostsYearRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsYearRoute: PostsYearRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface DashboardPostsRouteChildren {
  DashboardPostsPostIdRoute: typeof DashboardPostsPostIdRoute
}

const DashboardPostsRouteChildren: DashboardPostsRouteChildren = {
  DashboardPostsPostIdRoute: DashboardPostsPostIdRoute,
}

const DashboardPostsRouteWithChildren = DashboardPostsRoute._addFileChildren(
  DashboardPostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRouteWithChildren,
  WriteRoute: WriteRoute,
  DashboardPostsRoute: DashboardPostsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
