/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsYearRouteImport } from './routes/posts.$year'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as CreateMediaRouteImport } from './routes/create.media'
import { Route as CreateWriteChar123PostIdChar125RouteImport } from './routes/create.write.{-$postId}'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsYearRoute = PostsYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const CreateMediaRoute = CreateMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CreateRoute,
} as any)
const CreateWriteChar123PostIdChar125Route =
  CreateWriteChar123PostIdChar125RouteImport.update({
    id: '/write/{-$postId}',
    path: '/write/{-$postId}',
    getParentRoute: () => CreateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRouteWithChildren
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/create/media': typeof CreateMediaRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/create/write/{-$postId}': typeof CreateWriteChar123PostIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRouteWithChildren
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/create/media': typeof CreateMediaRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/create/write/{-$postId}': typeof CreateWriteChar123PostIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRouteWithChildren
  '/login': typeof LoginRoute
  '/posts': typeof PostsRouteWithChildren
  '/create/media': typeof CreateMediaRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/$year': typeof PostsYearRoute
  '/create/write/{-$postId}': typeof CreateWriteChar123PostIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/posts'
    | '/create/media'
    | '/posts/$postId'
    | '/posts/$year'
    | '/create/write/{-$postId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/posts'
    | '/create/media'
    | '/posts/$postId'
    | '/posts/$year'
    | '/create/write/{-$postId}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/posts'
    | '/create/media'
    | '/posts/$postId'
    | '/posts/$year'
    | '/create/write/{-$postId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRouteWithChildren
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$year': {
      id: '/posts/$year'
      path: '/$year'
      fullPath: '/posts/$year'
      preLoaderRoute: typeof PostsYearRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/create/media': {
      id: '/create/media'
      path: '/media'
      fullPath: '/create/media'
      preLoaderRoute: typeof CreateMediaRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/write/{-$postId}': {
      id: '/create/write/{-$postId}'
      path: '/write/{-$postId}'
      fullPath: '/create/write/{-$postId}'
      preLoaderRoute: typeof CreateWriteChar123PostIdChar125RouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateMediaRoute: typeof CreateMediaRoute
  CreateWriteChar123PostIdChar125Route: typeof CreateWriteChar123PostIdChar125Route
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateMediaRoute: CreateMediaRoute,
  CreateWriteChar123PostIdChar125Route: CreateWriteChar123PostIdChar125Route,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsYearRoute: typeof PostsYearRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsYearRoute: PostsYearRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRouteWithChildren,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
